#!/usr/bin/env python3
import os
import sys

_srcdir = '%s/src/' % os.path.dirname(os.path.realpath(__file__))
_filepath = os.path.dirname(sys.argv[0])
sys.path.insert(1, os.path.join(_filepath, _srcdir))

if sys.version_info[0] == 3:
    from scrapy_work import main

    if __name__ == '__main__':
        main.main()
else:
    print('请使用Python3')
    sys.exit(1)
